# ===========================================================
# 03 Conditionals
*Making decisions with Python*

## Objectives
- Trace the execution of unnested conditionals and conditionals inside loops.

## Use `if` Statements to Control Whether or not the Program Executes Code
- Structure is similar to a `for` statement:
  - First line opens with `if` and ends with a colon
  - The body contains one or more statements and is indented

In [1]:
mass = 3.54
if mass > 3.0:
    print(mass, 'is large')

3.54 is large


In [2]:
mass = 2.07
if mass > 3.0:
    print (mass, 'is large')

## You Can Nest Structures Within Each Other
- Follow Python's indentation rules to make more complicated code
- This is useful when we do not know all the items within a collection

In [3]:
masses = [3.54, 2.07, 9.22, 1.86, 1.71]
for m in masses:
    # 1. Write an if statement within this
    #    loop that prints "m is large" for
    #    each number, m, that is larger than 3.0.
    if m > 3.0:
        print(m, 'is large')

3.54 is large
9.22 is large


## Use `else` to Execute Code when an `if` condition is *not* True

In [4]:
masses = [3.54, 2.07, 9.22, 1.86, 1.71]
for m in masses:
    if m > 3.0:
        print(m, 'is large')
    else:
        print(m, 'is small')

3.54 is large
2.07 is small
9.22 is large
1.86 is small
1.71 is small


## Use `elif` to Create Multiple Tests
- `elif` allows us to provide many choices
- `elif` is short for "else if"
- `elif` is always associated with an `if`.
- `elif` must come before the `else`.

In [5]:
masses = [3.54, 2.07, 9.22, 1.86, 1.71]
for m in masses:
    # Print "m is HUGE" for each m
    # greater than five in the list above
    if m > 5.0:
        print(m, 'is HUGE')
    elif m > 3.0:
        print(m, 'is large')
    else:
        print(m, 'is small')

3.54 is large
2.07 is small
9.22 is HUGE
1.86 is small
1.71 is small


## Conditions are Tested Once and in Order

In [6]:
grade = 85
if grade >= 70:
    print('grade is C')
elif grade >= 80:
    print('grade is B')
elif grade >= 90:
    print('grade is A')

grade is C


- Conditionals *do not* automatically go back and re-evaluate if values change.

In [7]:
velocity = 10.0
if velocity > 20.0:
    print('moving too fast')
else:
    print('adjusting velocity')
    velocity = 50.0

adjusting velocity


In [8]:
print(velocity)

50.0


- You can use conditionals in a loop to update the values of variables.

In [9]:
velocity = 10.0
for i in range(5): # execute the loop 5 times
    print(i, ':', velocity)
    if velocity > 20.0:
        print('moving too fast')
        # Decrease the velociy by subtracting
        # 5 from `velocity`'s value.
        velocity = velocity - 5
    else:
        print('moving too slow')
        # Update `velocity` by adding
        # 10 to its current value
        velocity = velocity + 10
print('final velocity:', velocity)

0 : 10.0
moving too slow
1 : 20.0
moving too slow
2 : 30.0
moving too fast
3 : 25.0
moving too fast
4 : 20.0
moving too slow
final velocity: 30.0


## Exercise

1. What does this program print?
1. Copy the code into the next box
   and change the program so it prints `0.0`

```python
pressure = 71.9
if pressure > 50.0:
    pressure = 25.0
elif pressure <= 50.0:
    pressure = 0.0
print(pressure)
```

In [9]:
pressure = 71.9
if pressure > 50.0:
    pressure = 25.0
elif pressure <= 50.0:
    pressure = 0.0
print(pressure)

25.0


1. Since 71.9 is greater than 50.0, the first condition is true and `pressure` gets the value `25.0`. The `elif` does not execute, and the program prints 25.0 (see above).
1. See below.

In [10]:
# By changing the first value of `pressure` to any value
# less than or equal to 50.0, the program will print 0.0.
pressure = 5  # 5 <= 50.0 evaluates to True for the `elif` statement
if pressure > 50.0:
    pressure = 25.0
elif pressure <= 50.0:
    pressure = 0.0
print(pressure)

0.0


## Objectives
- Trace the execution of unnested conditionals and conditionals inside loops.